---
- name: Provision macOS
  hosts: all
  gather_facts: false

  tasks:

  - name: Inform user that automation is starting
    community.general.say:
      msg: 'Starting Ansible Automation'
      voice: Samantha

  - name: Include your list of software
    ansible.builtin.include_vars:
      file: data/vars.yml
    tags: always

  - name: Install software on Mac OS
    ansible.builtin.include_role:
      name: macos-provisioner
    tags: always

  - name: Inform user that automation finished
    community.general.say:
      msg: 'Finished provisioning your system. Enjoy!'
      voice: Samantha
