---
- name: Upgrade various elements of macOS system with one playbook
  hosts: localhost
  connection: local

  tasks:
    - name: Upgrade brew packages
      ansible.builtin.debug:
        msg: true
    - name: Upgrade pyenv virtual environment with latest packages
      ansible.builtin.debug:
        msg: true
    - name: Upgrade system updates
      ansible.builtin.debug:
        msg: true
    - name: Upgrade vagrant boxes and plugins
      ansible.builtin.debug:
        msg: true
    - name: What else?
      ansible.builtin.debug:
        msg: true
