---
- name: Install Tools - from Mac App Store
  ansible.builtin.command: "mas install {{ item }}"
  register: result
  changed_when: result.stdout | regex_search('already installed')
  with_items: "{{ software_mac_app_store }}"
  tags: app-store
  ignore_errors: true

# Would like to use just `homebrew` module to install any software
# However, homebrew module will report error with cask "is already installed".
# https://github.com/ansible-collections/community.general/pull/4177
- name: Install Tools - Casks # noqa ignore-errors
  community.general.homebrew_cask:
    name: "{{ software_homebrew_cask }}"
    state: present
  tags: cask
  ignore_errors: true

- name: Install Tools - Formulae # noqa ignore-errors
  community.general.homebrew:
    name: "{{ software_homebrew_formulae }}"
    state: present
  tags: formulae
  ignore_errors: true

# Note, `vagrant plugin install` command is not idempotent and always installs plugin
# https://github.com/hashicorp/vagrant/issues/12987
# Could do a wrapper and use `vagrant plugin list` or read `~/.vagrant.d/plugins.json`
- name: Install vagrant plugins
  ansible.builtin.command: "vagrant plugin install {{ item }}"
  register: result
  changed_when: result.stdout | regex_search('Installed the plugin')
  with_items: "{{ vagrant_plugins }}"
  tags: vagrant
  ignore_errors: true

- name: Ensure custom folders are created # noqa ignore-errors
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "u+rwx"
  loop: "{{ finder_folders }}"
  tags: finder
  ignore_errors: true

- name: Ensure side-bar items added to Finder
  ansible.builtin.command: "mysides add {{ item }}"
  register: result
  changed_when: result.stdout | regex_search('Installed the plugin')
  with_items: "{{ finder_sidebar }}"
  tags: finder
  ignore_errors: true

- name: Create shortcuts # noqa ignore-errors
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content }}"
    mode: "{{ item.mode }}"
  with_items: "{{ finder_shortcuts }}"
  tags: finder
  ignore_errors: true

- name: Create links # noqa ignore-errors
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    mode: "{{ item.mode }}"
  with_items: "{{ finder_links }}"
  tags: finder
  ignore_errors: true

# Change Mac OS User Preferences via Command Line
# https://pawelgrzybek.com/change-macos-user-preferences-via-command-line/
# Bear in mind that some changes require you to restart an app or, occasionally, a full reboot of the operating system
- name: Set system preferences # noqa ignore-errors
  ansible.builtin.command: "defaults write {{ item.domain }} {{ item.key }} {{ item.type }} {{ item.value }} && {{ item.reboot }}"
  with_items: "{{ system_prefs }}"
  tags: system
  changed_when: true
  ignore_errors: true
