# Office Applications - Documents, Spreadsheets, etc.
# --------------------------------------------------------
- name: Document Management - office suite
  homebrew_cask:
    name: libreoffice
    state: present

- name: Document Management - epub and pdf reader
  homebrew_cask:
    name: calibre
    state: present

# general document converter - http://pandoc.org/
#brew install pandoc
# pdfconvert - convert documents to pdf using Libre Office
# https://ask.libreoffice.org/en/question/12084/how-to-convert-documents-to-pdf-on-osx/
# example:
#pdfconvert <path+file>
## create script for easy use:
#cat <<EOF > /usr/local/bin/pdfconvert
##!/bin/bash
#/Applications/LibreOffice.app/Contents/MacOS/soffice --headless --convert-to pdf "\$@"
#EOF
#chmod +x /usr/local/bin/pdfconvert

# pdfmerge - merge pdf files
# http://gotofritz.net/blog/howto/joining-pdf-files-in-os-x-from-the-command-line/
# example:
# pdfmerge -o PATH/TO/YOUR/MERGED/FILE.pdf /PATH/TO/ORIGINAL/1.pdf /PATH/TO/ANOTHER/2.pdf /PATH/TO/A/WHOLE/DIR/*.pdf
# create symbolic link for easy use
#ln -s /System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py /usr/local/bin/pdfmerge
#chmod +x /usr/local/bin/pdfmerge
